# Setup
title:               arinyaho
tagline:             '이 순간은 영원하다'
description:         'it from bit'
url:                 https://arinyaho.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              arinyaho
  url:               https://linkedin.com/codeme
#  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
